from datetime import datetime
from typing import Literal, Protocol

from finbot_ingestion.domain import Artifact
from .pagination import Page

WorkKind = Literal["ACQUIRE", "PUBLISH"]


class ArtifactRepository(Protocol):
    async def create_if_absent(self, artifact: Artifact) -> bool: ...
    async def get(self, artifact_id: str) -> Artifact | None: ...
    async def mark_stored(self, artifact_id: str, s3_uri: str, stored_at: datetime,
                          content_type: str | None, size_bytes: int | None) -> None: ...
    async def mark_published(self, artifact_id: str, published_at: datetime) -> None: ...
    async def record_failure(self, artifact_id: str, error: str, at: datetime) -> None: ...
    async def list_pending(self, kind: WorkKind, *, page_size: int = 100,
                           token: str | None = None) -> Page[Artifact]: ...
    async def list_for_filing(self, accession_number: str, *, page_size: int = 100,
                              token: str | None = None) -> Page[Artifact]: ...
