from collections.abc import Sequence
from datetime import date, datetime
from typing import Protocol

from finbot_ingestion.domain import ExpectedEarningsEvent
from finbot_ingestion.calendar.contracts import CalendarSyncRun, CalendarSyncState, CalendarSyncSuccess


class CalendarRepository(Protocol):
    async def upsert_events(self, events: Sequence[ExpectedEarningsEvent]) -> None: ...
    async def get_events(self, start: datetime, end: datetime) -> list[ExpectedEarningsEvent]: ...
    async def get_event(self, expected_date: date, cik: str) -> ExpectedEarningsEvent | None: ...
    async def cancel_event(self, event: ExpectedEarningsEvent, *, at: datetime,
                           require_unchanged: bool = False) -> bool: ...
    async def get_sync_state(self, provider: str) -> CalendarSyncState | None: ...
    async def begin_sync(self, run: CalendarSyncRun) -> CalendarSyncRun: ...
    async def complete_sync(self, success: CalendarSyncSuccess) -> None: ...
    async def fail_sync(self, run: CalendarSyncRun, *, error: str, at: datetime) -> None: ...
