from datetime import datetime
from typing import Protocol

from finbot_ingestion.domain import Filing
from finbot_ingestion.domain.checkpoints import FilingCheckpoint
from .pagination import Page


class FilingRepository(Protocol):
    async def exists(self, accession_number: str) -> bool: ...
    async def create_if_absent(self, filing: Filing) -> bool: ...
    async def get(self, accession_number: str) -> Filing | None: ...
    async def get_checkpoint(self, accession_number: str) -> FilingCheckpoint | None: ...
    async def mark_enumerated(self, accession_number: str, *, primary_document_name: str,
                              artifact_count: int, completed_at: datetime) -> None: ...
    async def record_failure(self, accession_number: str, error: str, at: datetime) -> None: ...
    async def list_pending(self, *, page_size: int = 100, token: str | None = None) -> Page[Filing]: ...
